# UCS420: Cognitive Computing — Assignment 5

## NumPy — Introduction 1

Name: Vishu Verma  
Roll number: 1024170242

## Question 1

Create a 1D array with 5 elements and perform basic operations on it.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

Original array: [10 20 30 40 50]


In [2]:
# every operation works on the whole array at once, no loop needed
print("a) Add 2 to every element      :", arr + 2)
print("b) Multiply every element by 3 :", arr * 3)
print("c) Divide every element by 2   :", arr / 2)   # division always gives floats

a) Add 2 to every element      : [12 22 32 42 52]
b) Multiply every element by 3 : [ 30  60  90 120 150]
c) Divide every element by 2   : [ 5. 10. 15. 20. 25.]


In [3]:
print("The original array is untouched:", arr)   # the operations above returned new arrays

The original array is untouched: [10 20 30 40 50]


## Question 2

**a) Reverse the NumPy array.**

In [4]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original:", arr)
print("Reversed:", arr[::-1])   # a step of -1 walks the array backwards

Original: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]


**b) Find the most frequent value and its indices.**

In [5]:
def most_frequent(a):
    """Print the most frequent value(s) of an array and where they occur."""
    values, counts = np.unique(a, return_counts=True)
    highest = counts.max()
    winners = values[counts == highest]   # more than one value can share the top count

    print("Array :", a)
    print("Counts:", dict(zip(values.tolist(), counts.tolist())))
    for value in winners:
        print("Most frequent value:", value, "occurs", highest, "times at indices",
              np.where(a == value)[0])
    print()

In [6]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent(x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent(y)   # here 1 and 3 both appear 3 times, so both are printed

Array : [1 2 3 4 5 1 2 1 1 1]
Counts: {1: 5, 2: 2, 3: 1, 4: 1, 5: 1}
Most frequent value: 1 occurs 5 times at indices [0 5 7 8 9]

Array : [1 1 1 2 3 4 2 4 3 3]
Counts: {1: 3, 2: 2, 3: 3, 4: 2}
Most frequent value: 1 occurs 3 times at indices [0 1 2]
Most frequent value: 3 occurs 3 times at indices [4 8 9]



## Question 3

Access elements of a 2-D array using row and column indices.

(The array in the question needs one more pair of brackets around the three rows,
otherwise `np.array` reads them as three separate arguments.)

In [7]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
# indices start at 0, so the 1st row is index 0 and the 2nd column is index 1
print("a) 1st row, 2nd column:", arr[0, 1])
print("b) 3rd row, 1st column:", arr[2, 0])

a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


## Question 4

Create a 1-D array named `vishu` with 25 evenly spaced numbers from 10 to 100 using `linspace()`.

In [9]:
vishu = np.linspace(10, 100, 25)
print(vishu)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [10]:
print("Dimensions (ndim) :", vishu.ndim)
print("Shape             :", vishu.shape)
print("Total elements    :", vishu.size)
print("Data type         :", vishu.dtype)
print("Bytes per element :", vishu.itemsize)
print("Total bytes       :", vishu.nbytes)

Dimensions (ndim) : 1
Shape             : (25,)
Total elements    : 25
Data type         : float64
Bytes per element : 8
Total bytes       : 200


In [11]:
# transpose using reshape -- turn the row of 25 into a column of 25
transposed = vishu.reshape(25, 1)
print("Shape after reshape(25, 1):", transposed.shape)
print(transposed[:5], "...")

Shape after reshape(25, 1): (25, 1)
[[10.  ]
 [13.75]
 [17.5 ]
 [21.25]
 [25.  ]] ...


In [12]:
# can we do the same with T?
print("Shape of vishu.T:", vishu.T.shape)
print("Is vishu.T the same as vishu?", np.array_equal(vishu.T, vishu))

Shape of vishu.T: (25,)
Is vishu.T the same as vishu? True


**Answer:** No, `T` cannot do it here. Transposing swaps the axes, and a 1-D array has only one
axis, so `vishu.T` gives back the very same 25-element row. To get a column you have to add a
second axis, which is what `reshape(25, 1)` does (`vishu[:, np.newaxis]` works too). `T` only
transposes properly once the array is 2-D.

## Question 5

Create a 2-D array of three rows and four columns named `ucs420_vishu`.

In [13]:
ucs420_vishu = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])
print(ucs420_vishu)
print("Shape:", ucs420_vishu.shape)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Shape: (3, 4)


In [14]:
print("Mean            :", ucs420_vishu.mean())
print("Median          :", np.median(ucs420_vishu))
print("Max             :", ucs420_vishu.max())
print("Min             :", ucs420_vishu.min())
print("Unique elements :", np.unique(ucs420_vishu))

Mean            : 43.333333333333336
Median          : 37.5
Max             : 90
Min             : 10
Unique elements : [10 15 20 30 35 40 50 60 70 80 90]


In [15]:
reshaped_ucs420_vishu = ucs420_vishu.reshape(4, 3)
print("reshaped_ucs420_vishu (4 rows, 3 columns):")
print(reshaped_ucs420_vishu)

reshaped_ucs420_vishu (4 rows, 3 columns):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [16]:
resized_ucs420_vishu = np.resize(ucs420_vishu, (2, 3))
print("resized_ucs420_vishu (2 rows, 3 columns):")
print(resized_ucs420_vishu)

# reshape needs the element count to match (12 = 4x3), resize does not --
# 2x3 only holds 6 values, so resize keeps the first 6 and drops the rest
print("\nElements kept:", resized_ucs420_vishu.size, "out of", ucs420_vishu.size)

resized_ucs420_vishu (2 rows, 3 columns):
[[10 20 30]
 [40 50 60]]

Elements kept: 6 out of 12
